name: $(Date:yyyyMMdd)$(Rev:-rr)

trigger: 
  - uipath

pool:
  vmImage: 'windows-2022'
  demands:
  - msbuild
  - visualstudio

steps:
- task: CmdLine@2
  name: getVersions
  inputs:
    script: |
      call .ci\Scripts\getVars
      set
      
      cmake --version
      perl -v
      msbuild -version

- powershell: .\.ci\Scripts\getOpenSsl
  displayName: getOpenSsl
- powershell: .\.ci\Scripts\buildOpenSsl
  displayName: buildOpenSsl
- powershell: .\.ci\Scripts\buildFreeRDP
  displayName: buildFreeRDP
- powershell: .\.ci\Scripts\buildFreeRdpWrapper
  displayName: buildFreeRdpWrapper

- powershell: .\.ci\Scripts\TestFreeRdpClient.bat
  displayName: TestFreeRdpClient

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'VSTest' # Options: JUnit, NUnit, VSTest, xUnit, cTest
    testResultsFiles: '..\_temp\*.trx' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    mergeTestResults: true # Optional
    failTaskOnFailedTests: true # Optional
    #testRunTitle: # Optional
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    #publishRunAttachments: true # Optional

- task: DotNetCoreCLI@2
  displayName: 'build Session.Tests'
  inputs:
    command: 'test'
    arguments: '--no-build'
    projects: 'UiPath.FreeRdpClient\UiPath.FreeRdpClient.Tests\UiPath.FreeRdp.Tests.csproj'

- task: PublishPipelineArtifact@1
  name: publishFreeRDPWrapper
  inputs:
    targetPath: 'Output\bin' 
    artifactName: 'freeRdpWrapper'
    parallel: true

- task: PublishPipelineArtifact@1
  name: publishFreeRDPOnly
  inputs:
    targetPath: '.' 
    artifactName: 'freeRdpOnly' 
    parallel: true

- task: PublishPipelineArtifact@1
  name: publishOpenSSL32
  inputs:
    targetPath: '..\OpenSSL-VC-32' 
    artifactName: 'openSSL-32' 
    parallel: true

- task: PublishPipelineArtifact@1
  name: publishOpenSSL64
  inputs:
    targetPath: '..\OpenSSL-VC-64' 
    artifactName: 'openSSL-64' 
    parallel: true

