name: $(Date:yyyyMMdd)$(Rev:-rr)

trigger: 
  - uipath

pool:
  vmImage: 'windows-2022'
  demands:
  - msbuild
  - visualstudio

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'

- task: NuGetAuthenticate@0

- script: |
    call .ci\Scripts\getVars
   
    cmake --version
    perl -v
    msbuild -version

    set
  name: getVersions

- script: .\.ci\Scripts\getOpenSsl
  displayName: getOpenSsl
- script: .\.ci\Scripts\buildOpenSsl
  displayName: buildOpenSsl
- script: .\.ci\Scripts\buildFreeRDP
  displayName: buildFreeRDP

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'UiPath.FreeRdpClient\UiPath.FreeRdpClient.sln'

- task: MSBuild@1
  displayName: msbuild FreeRdpWrapper build
  inputs:
    solution: 'UiPath.FreeRdpClient\UiPath.FreeRdpClient.sln' 
    platform: 'x64'
    configuration: 'Release'
    msbuildArchitecture: 'x64'
    msbuildArguments: "/p:VersionSuffix=$(Build.BuildNumber)"

- task: DotNetCoreCLI@2
  displayName: 'Test FreeRdpClient'
  inputs:
    command: 'test'
    arguments: '--no-build /p:Configuration=Release'
    projects: 'UiPath.FreeRdpClient\UiPath.FreeRdpClient.Tests\UiPath.FreeRdp.Tests.csproj'

- task: NuGetCommand@2
  displayName: 'NuGet Push to UiPath-Internal'
  inputs:
    command: push
    packagesToPush: 'Output\nugets\UiPath.FreeRdpClient.*.nupkg'
    publishVstsFeed: '5b98d55c-1b14-4a03-893f-7a59746f1246/788028a9-5a01-48ee-b925-3af51ae46294'